preguntas = [
	"¿Qué infraestructura tecnológica utilizan para gestionar la gobernanza de datos?",
	"¿Qué herramientas de BI/BA utilizan para la explotación, visualización, almacenamiento y procesamiento de datos?",
	"¿Tienen un inventario de las herramientas y tecnologías utilizadas para la gestión de los datos (BBDD, análisis, ETL, gestión de metadatos, calidad de datos, etc)?",
	"¿Existe un inventario de activos de información?",
	"¿Tienen un catálogo de datos y/o de los conjuntos de datos?",
	"¿Cuentan con un sistema o proceso de gestión de metadatos?",
	"¿Cómo gestionan el inventario de datos y definiciones?",
	"¿Qué métodos o herramientas utilizan para capturar y gestionar metadatos?",
	"¿Tienen un diccionario de datos?",
	"¿Identifican y gestionan datos maestros y críticos?",
	"¿Documentan los procesos asociados?",
	"¿Han definido y aplicado estándares de industria o de negocio a los datos?",
	"¿Cómo garantizan la calidad de los datos a lo largo de su ciclo de vida?",
	"¿Utilizan herramientas o procesos para corregir problemas de calidad?",
	"¿Están documentados los procesos de calidad?",
	"¿Cuentan con métricas (KPI's) para evaluar la calidad de los datos?",
	"¿Cuáles son los desafíos actuales en términos de gestión y calidad de datos?",
	"¿Qué políticas existen para garantizar la integridad?",
	"¿Tienen definidos los roles o propietarios de los datos?",
	"¿Tienen políticas y procedimientos para la gestión del ciclo de vida?",
	"¿Existe una estrategia de respaldo y recuperación de datos?",
	"¿Documentan los procesos y procedimientos de gestión de datos?",
	"¿Implementan procesos de certificación de datos?",
	"¿Qué sistemas o herramientas utilizan?",
	"¿Tienen definidos roles o un área específica para la gestión de accesorios?",
	"¿Cuentan con políticas de seguridad de la información y gestión de accesos?",
	"¿Qué medidas de seguridad implementan para proteger datos sensibles?",
	"¿Documentan la política de seguridad y la matriz de roles?",
	"¿Gestionan los permisos y roles para garantizar el acceso adecuado?",
	"¿Tienen un área de seguridad alineada con el gobierno de datos?",
	"¿Incluyen a proveedores y terceros en los procesos/políticas de seguridad?",
	"¿Cómo abordan los requisitos de cumplimiento normativo en gestión y protección de datos?",
	"¿Qué tecnologías, procesos o procedimientos se tienen para auditar y asegurar el cumplimiento?",
	"¿Documentan los procesos relacionados con el cumplimiento de regulaciones y leyes de privacidad?",
	"¿Incluye a proveedores y terceros en sus procesos de cumplimiento?",
	"¿Se tiene inventario de las políticas, normatividad y/o procesos que aplican a la organización, tanto internos como para entes externos?",
	"¿Las políticas, procesos y/o procedimientos existentes, están alineados con la estrategia de negocio?",
	"¿Tienen políticas de gobierno de datos implementadas?",
	"¿Han supervisado o analizado la implementación de estas políticas?",
	"¿Qué informes y métricas existen para evaluar la eficacia de la gobernanza de datos?",
	"¿Cómo gestionan la solicitud, disposición y publicación de información?",
	"¿Documentan y controlan los resultados de la gestión de indicadores?",
	"¿Tienen inventario de informes, tableros e indicadores de gestión?",
	"¿Existe algún sitio donde repose la información relevante en cuanto a los seguimientos o cumplimiento de las necesidades del negocio con respecto a los datos?",
	"¿Tienen identificados dominios de información y roles asociados a cada dominio?",
	"¿Cuál es la composición del equipo interno para la iniciativa de gobierno de datos?",
	"¿Tienen inventario de fuentes de datos gobernadas y no gobernadas y de los activos de información?",
	"¿Documentan los procesos de solicitud, acceso y gestión de información?",
	"¿Cuentan con áreas de filtro para estas solicitudes (mesa de ayuda – aplicativos de gestión de tickets – árboles de tipología)?",
	"¿Se comunican los cambios, actualizaciones, novedades e iniciativas de gestión de datos a los stakeholders de cada área oa la organización en general?",
	"¿Cómo capacitan al personal técnico?",
	"¿Qué recursos tecnológicos utilizan para la profesionalización y transferencia de conocimiento?",
	"¿Las capacitaciones en lo que a datos o herramientas de gestión de datos se extienden a otras áreas de la empresa diferentes a las que componen TI?",
	"¿Qué programas de capacitación necesitan para el personal en gestión de datos?",
	"¿Cuentan con un plan de mantenimiento y actualización de procesos y tecnologías?",
	"¿Cuáles son los criterios para considerar el proyecto como exitoso?",
	"¿Han identificado problemas o casos de negocio que puedan servir como punto de partida para la estrategia de Gobierno de datos?",
	"¿Están alineadas las iniciativas de gobernanza de datos con otros proyectos o sistemas en la organización?",
	"¿Las iniciativas de gobernanza de datos están alineadas con las metas y visión de la organización?",
	"¿Hay alguna iniciativa de gestión o gobierno de datos en curso que deba ser considerada?"
]